from models import Config, FeatureGroup
from config_manager import ConfigManager

def generate_hlsl(config: Config) -> str:
    output = [config.prefix + "\n"] if config.prefix else []
    output.append("// Generated by Shader Platform Macro Generator (https://github.com/JasonMa0012/ShaderPlatformMacroGenerator)")
    output.append("// Unity Builtin Macros: https://docs.unity3d.com/2022.3/Documentation/Manual/SL-BuiltinMacros.html")
    output.append("// Unreal Builtin Macros: Engine/Shaders/Public/Platform.ush")
    output.append("")
    output.append(f"#ifndef {config.file_include_macro}")
    output.append(f"    #define {config.file_include_macro}\n")
    
    
    # Platform
    for i, platform in enumerate(config.platforms):
        output.append(f"    {"#if" if i == 0 else "#elif"} {' '.join([macro for macro in platform.macros])}")
        
        # Quality
        for i_quality, quality in enumerate(config.qualities):
            output.append(f"        {"#if" if i_quality == 0 else "#elif"} {' '.join([macro for macro in quality.macros])}")
            
            # Feature
            for group in config.feature_groups:
                for feature in group.features:
                    value = config.get_feature_state(platform, quality, feature)
                    for macro in feature.macros:
                        output.append(f"            #define {macro} {int(value)}")
        
        output.append("        #endif")
    
    output.append("    #endif\n")
    output.append(f"#endif // {config.file_include_macro}")
    
    return '\n'.join(output) + ("\n" + config.postfix if config.postfix else "")