// Generated by Shader Platform Macro Generator (https://github.com/JasonMa0012/ShaderPlatformMacroGenerator)

#ifndef PLATFORM_FEATURE_MACRO_INCLUDE
    #define PLATFORM_FEATURE_MACRO_INCLUDE

    #if (defined(PLATFORM_PC) || defined(SHADER_API_DX11))
        #if (defined(QUALITY_HIGH) || defined(QUALITY_ULTRA))
            #define FEATURE_TESSELLATION 1
            #define ENABLE_GEOMETRY_SHADER 1
            #define FEATURE_RAY_MARCHING 1
            #define FEATURE_SUBSURFACE 1
        #elif (defined(QUALITY_LOW))
            #define FEATURE_TESSELLATION 0
            #define ENABLE_GEOMETRY_SHADER 0
            #define FEATURE_RAY_MARCHING 0
            #define FEATURE_SUBSURFACE 0
        #endif
    #elif (defined(PLATFORM_IOS))
        #if (defined(QUALITY_HIGH) || defined(QUALITY_ULTRA))
            #define FEATURE_TESSELLATION 1
            #define ENABLE_GEOMETRY_SHADER 1
            #define FEATURE_RAY_MARCHING 1
            #define FEATURE_SUBSURFACE 1
        #elif (defined(QUALITY_LOW))
            #define FEATURE_TESSELLATION 0
            #define ENABLE_GEOMETRY_SHADER 0
            #define FEATURE_RAY_MARCHING 0
            #define FEATURE_SUBSURFACE 0
        #endif
    #endif

#endif // PLATFORM_FEATURE_MACRO_INCLUDE